### PR TITLE
Introduce feature extraction from Resnets.

### PR DESCRIPTION
**Pull request by karandesai-96**
This PR introduces feature extraction through ResNets. Significant additions and modifications are as follows:

_**Note:** Several files have been renamed to avoid confusion or have a better semantic meaning since feature extraction through vgg16 and ResNets is slightly different._

1. The installation script (**download_vgg16.sh** -> **download_model.sh**) can download VGG 16, 19 and ResNet 18, 34, 50, 101, 152, 200 models. ResNet t7 models are taken from [facebook's repository](https://www.github.com/facebook/fb.resnet.torch).

2. The work done in **prepro_img.lua** has been shifted to **prepro_utils.lua** - there's a method named `extractFeatures` which accepts a `model` object, `opt` and output dims, and finally writes all the features after extracting them, to an HDF file.

3. This **prepro_utils.lua** is used by two files - **prepro_img_vgg16.lua** and **prepro_img_resnet.lua**. These files have identical structure - read model from either caffemodel or t7 files and truncate last few layers up to the layer of interest for feature extraction, and further simply call `extractFeatures`.

4. There was a separate script **prepro_img_pool5.lua** for extracting spatial features needed by `mn-att-ques-im-hist`. Some generalizations have been made to eliminate the requirement of a separate script and **prepro_img_vgg16.lua** can be reused - avoiding code duplication.
    - `ndims` which were hardcoded to 4096 for VGG16 are now inferred automatically. After truncating last few layers, a dummy tensor is passed to the model and shape of output is accepted as `ndims` (ignoring the "batch" dimension).
    - `ndims` are `{4096}` for `VGG16 - relu7`, `{2048}` for `ResNet 200`, and `{14, 14, 512}` for `VGG16 - pool5` which are consistent with the previously hardcoded values.

Finally, all the changes have been suitable reflected in **README**. I'll be performing the experiments with ResNet features, and will collect all results in a markdown file and submit a PR later. Until then this is a working piece of code so far which I'm using for an extended set of experiments.

### CODE REVIEW

**Comment by karandesai-96** [comment]
The recent commit on introducing `-saveIter` and `-weightInit` in **opts.lua** would cause an error in loading models trained before that commit.

**Comment by abhshkdz** [comment]
This was a fairly clean PR for the most part, except for [this bug](https://github.com/batra-mlp-lab/visdial/commit/8e758924963614d7fa22b34cc3d461c49b4f39cd).

Thanks for this @karandesai-96, we now have ResNet-support! :)

**Comment by satwikkottur** [comment]
@karandesai-96 Thanks for the PR! Curious, did you compute the accuracy numbers for any of the models with ResNet features?

**Comment by karandesai-96** [comment]
@satwikkottur Yes I did. I trained all the the generative models with QIH as input. Here are the reported metrics with ResNet features per checkpoint, for HRE-QIH-G (please note the change in batchsize and initialization strategy mentioned in figure)

https://goo.gl/1hkaah

I collected all other checkpoints too (LF-QIH-G and MN-QIH-G) but someone else `rm -rf`ed the directory and I haven't got the chance to set up again.

**Pull request merged**
